# Data Configuration
data_path: "artifacts/train.csv"           # Path ke dataset

data:

  preprocessing_path: "models/preprocessing" # Path untuk preprocessing model
  target_column: "SalePrice"                 # Kolom target untuk prediksi
  required_columns:                          # Kolom yang wajib ada
    - Id
    - MSSubClass
    - MSZoning
    - LotFrontage
    - LotArea
    - Street
    - SalePrice

# Preprocessing Configuration
categorical_features:
  - "MSZoning"
  - "Street"

numerical_features:
  - "LotFrontage"
  - "LotArea"

model_params:
  decision_tree:
    max_depth: 5
    min_samples_split: 2
    random_state: 42
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    random_state: 42
  
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42


# MLflow Configuration
mlflow:
  tracking_uri: "sqlite:///mlflow.db"        # MLflow database
  experiment_name: "house_price_experiment" # Nama eksperimen di MLflow


# API Configuration
api:
  title: "House Price Prediction API"
  description: "API for predicting house prices"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8000
